In [5]:
import pandas as pd
import csv

In [2]:
with open('d:\\atom\\exp\\20210227\\60cm_double_oil.csv', 'r') as fp:
    print(fp)

<_io.TextIOWrapper name='d:\\atom\\exp\\20210227\\60cm_double_oil.csv' mode='r' encoding='cp936'>

In [4]:
with open('https://raw.githubusercontent.com/ine-rmotr-curriculum/RDP-Reading-Data-with-Python-and-Pandas/master/unit-1-reading-data-with-python-and-pandas/lesson-1-reading-csv-and-txt-files/files/exam_review.csv', 'r') as fp:
    for index, line in enumerate(fp.readlines()):
        if (index < 10):
            print(line)

OSError: [Errno 22] Invalid argument: 'https://raw.githubusercontent.com/ine-rmotr-curriculum/RDP-Reading-Data-with-Python-and-Pandas/master/unit-1-reading-data-with-python-and-pandas/lesson-1-reading-csv-and-txt-files/files/exam_review.csv'

https://raw.githubusercontent.com/ine-rmotr-curriculum/RDP-Reading-Data-with-Python-and-Pandas/master/unit-1-reading-data-with-python-and-pandas/lesson-1-reading-csv-and-txt-files/files/exam_review.csv

In [6]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: Union[str, pathlib.Path, IO[~AnyStr]],
    sep=',',
    delimiter=None,
    header='infer',
    names=None,
    index_col=None,
    usecols=None,
    squeeze=False,
    prefix=None,
    mangle_dupe_cols=True,
    dtype=None,
    engine=None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=False,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    cache_dates=True,
    iterator=False,
    chunksize=None,
    compression='infer',
    thousands=None,
    decimal: str = '.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    escapechar=None,
    comment=None,
    encoding=None,
    dialect=None,
    error_bad_lines=True,
    warn_bad_lines=True,
    delim_whitespace=False,
    low_memory=True,
    memory_map=False,
    float_precision=None,
)
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handler (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Delimiter to use. If sep is None, the C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator by Python's builtin sniffer
    tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
    different from ``'\s+'`` will be interpreted as regular expressions and
    will also force the use of the Python parsing engine. Note that regex
    delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, default ``None``
    Alias for sep.
header : int, list of int, default 'infer'
    Row number(s) to use as the column names, and the start of the
    data.  Default behavior is to infer the column names: if no names
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a multi-index on the columns
    e.g. [0,1,3]. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : array-like, optional
    List of column names to use. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : int, str, sequence of int / str, or False, default ``None``
  Column(s) to use as the row labels of the ``DataFrame``, either given as
  string name or column index. If a sequence of int / str is given, a
  MultiIndex is used.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g. when you have a malformed file with delimiters at
  the end of each line.
usecols : list-like or callable, optional
    Return a subset of the columns. If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in `names` or
    inferred from the document header row(s). For example, a valid list-like
    `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a DataFrame from ``data`` with element order preserved use
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
    in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to True. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
squeeze : bool, default False
    If the parsed data only contains one column then return a Series.
prefix : str, optional
    Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
mangle_dupe_cols : bool, default True
    Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
    'X'...'X'. Passing in False will cause data to be overwritten if there
    are duplicate names in the columns.
dtype : Type name or dict of column -> type, optional
    Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
    'c': 'Int64'}
    Use `str` or `object` together with suitable `na_values` settings
    to preserve and not interpret dtype.
    If converters are specified, they will be applied INSTEAD
    of dtype conversion.
engine : {'c', 'python'}, optional
    Parser engine to use. The C engine is faster while the python engine is
    currently more feature-complete.
converters : dict, optional
    Dict of functions for converting values in certain columns. Keys can either
    be integers or column labels.
true_values : list, optional
    Values to consider as True.
false_values : list, optional
    Values to consider as False.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : list-like, int or callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (int)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning True if the row should be skipped and False otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with engine='c').
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : scalar, str, list-like, or dict, optional
    Additional strings to recognize as NA/NaN. If dict passed, specific
    per-column NA values.  By default the following values are interpreted as
    NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
    '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a',
    'nan', 'null'.
keep_default_na : bool, default True
    Whether or not to include the default NaN values when parsing the data.
    Depending on whether `na_values` is passed in, the behavior is as follows:

    * If `keep_default_na` is True, and `na_values` are specified, `na_values`
      is appended to the default NaN values used for parsing.
    * If `keep_default_na` is True, and `na_values` are not specified, only
      the default NaN values are used for parsing.
    * If `keep_default_na` is False, and `na_values` are specified, only
      the NaN values specified `na_values` are used for parsing.
    * If `keep_default_na` is False, and `na_values` are not specified, no
      strings will be parsed as NaN.

    Note that if `na_filter` is passed in as False, the `keep_default_na` and
    `na_values` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of na_values). In
    data without any NAs, passing na_filter=False can improve the performance
    of reading a large file.
verbose : bool, default False
    Indicate number of NA values placed in non-numeric columns.
skip_blank_lines : bool, default True
    If True, skip over blank lines rather than interpreting as NaN values.
parse_dates : bool or list of int or names or list of lists or dict, default False
    The behavior is as follows:

    * boolean. If True -> try parsing the index.
    * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
      a single date column.
    * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
      result 'foo'

    If a column or index cannot be represented as an array of datetimes,
    say because of an unparseable value or a mixture of timezones, the column
    or index will be returned unaltered as an object data type. For
    non-standard datetime parsing, use ``pd.to_datetime`` after
    ``pd.read_csv``. To parse an index or column with a mixture of timezones,
    specify ``date_parser`` to be a partially-applied
    :func:`pandas.to_datetime` with ``utc=True``. See
    :ref:`io.csv.mixed_timezones` for more.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If True and `parse_dates` is enabled, pandas will attempt to infer the
    format of the datetime strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.
keep_date_col : bool, default False
    If True and `parse_dates` specifies combining multiple columns then
    keep the original columns.
date_parser : function, optional
    Function to use for converting a sequence of string columns to an array of
    datetime instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. Pandas will try to call `date_parser` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by `parse_dates` into a single array
    and pass that; and 3) call `date_parser` once for each row using one or
    more strings (corresponding to the columns defined by `parse_dates`) as
    arguments.
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If True, use a cache of unique, converted dates to apply the datetime
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

    .. versionadded:: 0.25.0
iterator : bool, default False
    Return TextFileReader object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Return TextFileReader object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.
compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and
    `filepath_or_buffer` is path-like, then detect compression from the
    following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
    decompression). If using 'zip', the ZIP file must contain only one data
    file to be read in. Set to None for no decompression.
thousands : str, optional
    Thousands separator.
decimal : str, default '.'
    Character to recognize as decimal point (e.g. use ',' for European data).
lineterminator : str (length 1), optional
    Character to break file into lines. Only valid with C parser.
quotechar : str (length 1), optional
    The character used to denote the start and end of a quoted item. Quoted
    items can include the delimiter and it will be ignored.
quoting : int or csv.QUOTE_* instance, default 0
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
    QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
doublequote : bool, default ``True``
   When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive quotechar elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    One-character string used to escape other characters.
comment : str, optional
    Indicates remainder of line should not be parsed. If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter `header` but not by
    `skiprows`. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
    treated as the header.
encoding : str, optional
    Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .
dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: `delimiter`, `doublequote`, `escapechar`,
    `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
    override values, a ParserWarning will be issued. See csv.Dialect
    documentation for more details.
error_bad_lines : bool, default True
    Lines with too many fields (e.g. a csv line with too many commas) will by
    default cause an exception to be raised, and no DataFrame will be returned.
    If False, then these "bad lines" will dropped from the DataFrame that is
    returned.
warn_bad_lines : bool, default True
    If error_bad_lines is False, and warn_bad_lines is True, a warning for each
    "bad line" will be output.
delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
    used as the sep. Equivalent to setting ``sep='\s+'``. If this option
    is set to True, nothing should be passed in for the ``delimiter``
    parameter.
low_memory : bool, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set False, or specify the type with the `dtype` parameter.
    Note that the entire file is read into a single DataFrame regardless,
    use the `chunksize` or `iterator` parameter to return the data in chunks.
    (Only valid with C parser).
memory_map : bool, default False
    If a filepath is provided for `filepath_or_buffer`, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.
float_precision : str, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are `None` for the ordinary converter,
    `high` for the high-precision converter, and `round_trip` for the
    round-trip converter.

Returns
-------
DataFrame or TextParser
    A comma-separated values (csv) file is returned as two-dimensional
    data structure with labeled axes.

See Also
--------
to_csv : Write DataFrame to a comma-separated values (csv) file.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_fwf : Read a table of fixed-width formatted lines into DataFrame.

Examples
--------
>>> pd.read_csv('data.csv')  # doctest: +SKIP
File:      d:\programdata\anaconda3\lib\site-packages\pandas\io\parsers.py
Type:      function

In [28]:
df = pd.read_csv('https://raw.githubusercontent.com/ine-rmotr-curriculum/RDP-Reading-Data-with-Python-and-Pandas/master/unit-1-reading-data-with-python-and-pandas/lesson-1-reading-csv-and-txt-files/files/exam_review.csv', sep='>')
df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

In [24]:
df = pd.DataFrame(data={'Col1': [1, None, 3, 4], 'Col2': [1, 4, 6, 8]})
df

   Col1  Col2
0   1.0     1
1   NaN     4
2   3.0     6
3   4.0     8

In [25]:
df.corr()

          Col1      Col2
Col1  1.000000  0.998625
Col2  0.998625  1.000000

In [14]:
import numpy as np

In [29]:
import sqlite3

In [34]:
conn = sqlite3.connect('chinook.db')

In [36]:
cur = conn.cursor()

In [37]:
cur.execute('SELECT * FROM employees LIMIT 5')

In [38]:
results = cur.fetchall()
results

[(1,
  'Adams',
  'Andrew',
  'General Manager',
  None,
  '1962-02-18 00:00:00',
  '2002-08-14 00:00:00',
  '11120 Jasper Ave NW',
  'Edmonton',
  'AB',
  'Canada',
  'T5K 2N1',
  '+1 (780) 428-9482',
  '+1 (780) 428-3457',
  'andrew@chinookcorp.com'),
 (2,
  'Edwards',
  'Nancy',
  'Sales Manager',
  1,
  '1958-12-08 00:00:00',
  '2002-05-01 00:00:00',
  '825 8 Ave SW',
  'Calgary',
  'AB',
  'Canada',
  'T2P 2T3',
  '+1 (403) 262-3443',
  '+1 (403) 262-3322',
  'nancy@chinookcorp.com'),
 (3,
  'Peacock',
  'Jane',
  'Sales Support Agent',
  2,
  '1973-08-29 00:00:00',
  '2002-04-01 00:00:00',
  '1111 6 Ave SW',
  'Calgary',
  'AB',
  'Canada',
  'T2P 5M5',
  '+1 (403) 262-3443',
  '+1 (403) 262-6712',
  'jane@chinookcorp.com'),
 (4,
  'Park',
  'Margaret',
  'Sales Support Agent',
  2,
  '1947-09-19 00:00:00',
  '2003-05-03 00:00:00',
  '683 10 Street SW',
  'Calgary',
  'AB',
  'Canada',
  'T2P 5G3',
  '+1 (403) 263-4423',
  '+1 (403) 263-4289',
  'margaret@chinookcorp.com'),
 (5,
  'Johnson',
  'Steve',
  'Sales Support Agent',
  2,
  '1965-03-03 00:00:00',
  '2003-10-17 00:00:00',
  '7727B 41 Ave',
  'Calgary',
  'AB',
  'Canada',
  'T3B 1Y7',
  '1 (780) 836-9987',
  '1 (780) 836-9543',
  'steve@chinookcorp.com')]

In [42]:
df = pd.read_sql('SELECT * FROM employees;', conn,
                index_col='EmployeeId',
                parse_dates=['BirthDate', 'HireDate'])
df

,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
EmployeeId,,,,,,,,,,,,,,
1,Adams,Andrew,General Manager,NaN,1962-02-18,2002-08-14,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
2,Edwards,Nancy,Sales Manager,1.0,1958-12-08,2002-05-01,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29,2002-04-01,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
4,Park,Margaret,Sales Support Agent,2.0,1947-09-19,2003-05-03,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03,2003-10-17,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
6,Mitchell,Michael,IT Manager,1.0,1973-07-01,2003-10-17,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
7,King,Robert,IT Staff,6.0,1970-05-29,2004-01-02,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
8,Callahan,Laura,IT Staff,6.0,1968-01-09,2004-03-04,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8 entries, 1 to 8
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LastName    8 non-null      object
 1   FirstName   8 non-null      object
 2   Title       8 non-null      object
 3   ReportsTo   7 non-null      float64
 4   BirthDate   8 non-null      datetime64[ns]
 5   HireDate    8 non-null      datetime64[ns]
 6   Address     8 non-null      object
 7   City        8 non-null      object
 8   State       8 non-null      object
 9   Country     8 non-null      object
 10  PostalCode  8 non-null      object
 11  Phone       8 non-null      object
 12  Fax         8 non-null      object
 13  Email       8 non-null      object
dtypes: datetime64[ns](2), float64(1), object(11)
memory usage: 960.0+ bytes

In [44]:
df.to_sql?

Signature:
df.to_sql(
    name: str,
    con,
    schema=None,
    if_exists: str = 'fail',
    index: bool = True,
    index_label=None,
    chunksize=None,
    dtype=None,
    method=None,
) -> None
Docstring:
Write records stored in a DataFrame to a SQL database.

Databases supported by SQLAlchemy [1]_ are supported. Tables can be
newly created, appended to, or overwritten.

Parameters
----------
name : str
    Name of SQL table.
con : sqlalchemy.engine.Engine or sqlite3.Connection
    Using SQLAlchemy makes it possible to use any DB supported by that
    library. Legacy support is provided for sqlite3.Connection objects. The user
    is responsible for engine disposal and connection closure for the SQLAlchemy
    connectable See `here                 <https://docs.sqlalchemy.org/en/13/core/connections.html>`_

schema : str, optional
    Specify the schema (if database flavor supports this). If None, use
    default schema.
if_exists : {'fail', 'replace', 'append'}, default 'fail'
    How to behave if the table already exists.

    * fail: Raise a ValueError.
    * replace: Drop the table before inserting new values.
    * append: Insert new values to the existing table.

index : bool, default True
    Write DataFrame index as a column. Uses `index_label` as the column
    name in the table.
index_label : str or sequence, default None
    Column label for index column(s). If None is given (default) and
    `index` is True, then the index names are used.
    A sequence should be given if the DataFrame uses MultiIndex.
chunksize : int, optional
    Specify the number of rows in each batch to be written at a time.
    By default, all rows will be written at once.
dtype : dict or scalar, optional
    Specifying the datatype for columns. If a dictionary is used, the
    keys should be the column names and the values should be the
    SQLAlchemy types or strings for the sqlite3 legacy mode. If a
    scalar is provided, it will be applied to all columns.
method : {None, 'multi', callable}, optional
    Controls the SQL insertion clause used:

    * None : Uses standard SQL ``INSERT`` clause (one per row).
    * 'multi': Pass multiple values in a single ``INSERT`` clause.
    * callable with signature ``(pd_table, conn, keys, data_iter)``.

    Details and a sample callable implementation can be found in the
    section :ref:`insert method <io.sql.method>`.

    .. versionadded:: 0.24.0

Raises
------
ValueError
    When the table already exists and `if_exists` is 'fail' (the
    default).

See Also
--------
read_sql : Read a DataFrame from a table.

Notes
-----
Timezone aware datetime columns will be written as
``Timestamp with timezone`` type with SQLAlchemy if supported by the
database. Otherwise, the datetimes will be stored as timezone unaware
timestamps local to the original timezone.

.. versionadded:: 0.24.0

References
----------
.. [1] http://docs.sqlalchemy.org
.. [2] https://www.python.org/dev/peps/pep-0249/

Examples
--------

Create an in-memory SQLite database.

>>> from sqlalchemy import create_engine
>>> engine = create_engine('sqlite://', echo=False)

Create a table from scratch with 3 rows.

>>> df = pd.DataFrame({'name' : ['User 1', 'User 2', 'User 3']})
>>> df
     name
0  User 1
1  User 2
2  User 3

>>> df.to_sql('users', con=engine)
>>> engine.execute("SELECT * FROM users").fetchall()
[(0, 'User 1'), (1, 'User 2'), (2, 'User 3')]

>>> df1 = pd.DataFrame({'name' : ['User 4', 'User 5']})
>>> df1.to_sql('users', con=engine, if_exists='append')
>>> engine.execute("SELECT * FROM users").fetchall()
[(0, 'User 1'), (1, 'User 2'), (2, 'User 3'),
 (0, 'User 4'), (1, 'User 5')]

Overwrite the table with just ``df1``.

>>> df1.to_sql('users', con=engine, if_exists='replace',
...            index_label='id')
>>> engine.execute("SELECT * FROM users").fetchall()
[(0, 'User 4'), (1, 'User 5')]

Specify the dtype (especially useful for integers with missing values).
Notice that while pandas is forced to store the data as floating point,
the database supports nullable integers. When fetching the data with
Python, we get back integer scalars.

>>> df = pd.DataFrame({"A": [1, None, 2]})
>>> df
     A
0  1.0
1  NaN
2  2.0

>>> from sqlalchemy.types import Integer
>>> df.to_sql('integers', con=engine, index=False,
...           dtype={"A": Integer()})

>>> engine.execute("SELECT * FROM integers").fetchall()
[(1,), (None,), (2,)]
File:      d:\programdata\anaconda3\lib\site-packages\pandas\core\generic.py
Type:      method

In [46]:
df.to_csv?

Signature:
df.to_csv(
    path_or_buf: Union[str, pathlib.Path, IO[~AnyStr], NoneType] = None,
    sep: str = ',',
    na_rep: str = '',
    float_format: Union[str, NoneType] = None,
    columns: Union[Sequence[Union[Hashable, NoneType]], NoneType] = None,
    header: Union[bool, List[str]] = True,
    index: bool = True,
    index_label: Union[bool, str, Sequence[Union[Hashable, NoneType]], NoneType] = None,
    mode: str = 'w',
    encoding: Union[str, NoneType] = None,
    compression: Union[str, Mapping[str, str], NoneType] = 'infer',
    quoting: Union[int, NoneType] = None,
    quotechar: str = '"',
    line_terminator: Union[str, NoneType] = None,
    chunksize: Union[int, NoneType] = None,
    date_format: Union[str, NoneType] = None,
    doublequote: bool = True,
    escapechar: Union[str, NoneType] = None,
    decimal: Union[str, NoneType] = '.',
) -> Union[str, NoneType]
Docstring:
Write object to a comma-separated values (csv) file.

.. versionchanged:: 0.24.0
    The order of arguments for Series was changed.

Parameters
----------
path_or_buf : str or file handle, default None
    File path or object, if None is provided the result is returned as
    a string.  If a file object is passed it should be opened with
    `newline=''`, disabling universal newlines.

    .. versionchanged:: 0.24.0

       Was previously named "path" for Series.

sep : str, default ','
    String of length 1. Field delimiter for the output file.
na_rep : str, default ''
    Missing data representation.
float_format : str, default None
    Format string for floating point numbers.
columns : sequence, optional
    Columns to write.
header : bool or list of str, default True
    Write out the column names. If a list of strings is given it is
    assumed to be aliases for the column names.

    .. versionchanged:: 0.24.0

       Previously defaulted to False for Series.

index : bool, default True
    Write row names (index).
index_label : str or sequence, or False, default None
    Column label for index column(s) if desired. If None is given, and
    `header` and `index` are True, then the index names are used. A
    sequence should be given if the object uses MultiIndex. If
    False do not print fields for index names. Use index_label=False
    for easier importing in R.
mode : str
    Python write mode, default 'w'.
encoding : str, optional
    A string representing the encoding to use in the output file,
    defaults to 'utf-8'.
compression : str or dict, default 'infer'
    If str, represents compression mode. If dict, value at 'method' is
    the compression mode. Compression mode may be any of the following
    possible values: {'infer', 'gzip', 'bz2', 'zip', 'xz', None}. If
    compression mode is 'infer' and `path_or_buf` is path-like, then
    detect compression mode from the following extensions: '.gz',
    '.bz2', '.zip' or '.xz'. (otherwise no compression). If dict given
    and mode is 'zip' or inferred as 'zip', other entries passed as
    additional compression options.

    .. versionchanged:: 1.0.0

       May now be a dict with key 'method' as compression mode
       and other entries as additional compression options if
       compression mode is 'zip'.

quoting : optional constant from csv module
    Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
    then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
    will treat them as non-numeric.
quotechar : str, default '\"'
    String of length 1. Character used to quote fields.
line_terminator : str, optional
    The newline character or character sequence to use in the output
    file. Defaults to `os.linesep`, which depends on the OS in which
    this method is called ('\n' for linux, '\r\n' for Windows, i.e.).

    .. versionchanged:: 0.24.0
chunksize : int or None
    Rows to write at a time.
date_format : str, default None
    Format string for datetime objects.
doublequote : bool, default True
    Control quoting of `quotechar` inside a field.
escapechar : str, default None
    String of length 1. Character used to escape `sep` and `quotechar`
    when appropriate.
decimal : str, default '.'
    Character recognized as decimal separator. E.g. use ',' for
    European data.

Returns
-------
None or str
    If path_or_buf is None, returns the resulting csv format as a
    string. Otherwise returns None.

See Also
--------
read_csv : Load a CSV file into a DataFrame.
to_excel : Write DataFrame to an Excel file.

Examples
--------
>>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
...                    'mask': ['red', 'purple'],
...                    'weapon': ['sai', 'bo staff']})
>>> df.to_csv(index=False)
'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'

Create 'out.zip' containing 'out.csv'

>>> compression_opts = dict(method='zip',
...                         archive_name='out.csv')  # doctest: +SKIP
>>> df.to_csv('out.zip', index=False,
...           compression=compression_opts)  # doctest: +SKIP
File:      d:\programdata\anaconda3\lib\site-packages\pandas\core\generic.py
Type:      method

In [47]:
import lxml

In [48]:
html_string = """
<table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>Region</th> 
        <th>Item</th>
        <th>Units</th>
        <th>Unit cost</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1/6/2018</td>
        <td>East</td> 
        <td>Pencil</td>
        <td>95</td>
        <td>1.99</td>
      </tr>
      <tr>
        <td>1/23/2018</td>
        <td>Central</td> 
        <td>Binder</td>
        <td>50</td>
        <td>19.99</td>
      </tr>
      <tr>
        <td>2/9/2018</td>
        <td>Central</td> 
        <td>Pencil</td>
        <td>36</td>
        <td>4.99</td>
      </tr>
      <tr>
        <td>3/15/2018</td>
        <td>West</td> 
        <td>Pen</td>
        <td>27</td>
        <td>19.99</td>
      </tr>
    </tbody>
</table>
"""

In [49]:
from IPython.core.display import display, HTML
display(HTML(html_string))

In [50]:
dfs = pd.read_html(html_string)
dfs

[  Order date   Region    Item  Units  Unit cost
 0   1/6/2018     East  Pencil     95       1.99
 1  1/23/2018  Central  Binder     50      19.99
 2   2/9/2018  Central  Pencil     36       4.99
 3  3/15/2018     West     Pen     27      19.99]

In [51]:
dfs[0]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

In [53]:
html_url = 'https://www.basketball-reference.com/leagues/NBA_2019_per_game.html'
nba_tables = pd.read_html(html_url)

In [54]:
len(nba_tables)

1

In [55]:
nba = nba_tables[0]

In [56]:
nba.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [57]:
nba.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [58]:
nba.head(40)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,PG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
22,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7
25,23,Trevor Ariza,SF,33,TOT,69,69,34.0,4.3,10.7,...,.793,0.7,4.7,5.4,3.7,1.3,0.3,1.5,1.9,12.5
26,23,Trevor Ariza,SF,33,PHO,26,26,34.0,3.3,8.7,...,.837,0.6,5.0,5.6,3.3,1.5,0.3,1.5,1.7,9.9
27,23,Trevor Ariza,SF,33,WAS,43,43,34.1,4.8,11.8,...,.777,0.8,4.5,5.3,3.8,1.2,0.3,1.6,2.0,14.1
28,24,D.J. Augustin,PG,31,ORL,81,81,28.0,3.9,8.4,...,.866,0.5,2.0,2.5,5.3,0.6,0.0,1.6,1.4,11.7
29,25,Deandre Ayton,C,20,PHO,71,70,30.7,7.2,12.3,...,.746,3.1,7.1,10.3,1.8,0.9,0.9,1.8,2.9,16.3
30,26,Dwayne Bacon,SG,23,CHO,43,13,17.7,2.8,6.0,...,.739,0.2,1.9,2.1,1.1,0.3,0.1,0.4,1.7,7.3
31,27,Marvin Bagley III,PF,19,SAC,62,4,25.3,5.7,11.4,...,.691,2.6,5.0,7.6,1.0,0.5,1.0,1.6,1.9,14.9
32,28,Ron Baker,SG,25,TOT,15,0,10.1,0.3,1.3,...,.833,0.1,0.7,0.7,1.0,0.4,0.1,0.3,1.2,0.9
33,28,Ron Baker,SG,25,NYK,11,0,9.7,0.4,1.5,...,.833,0.1,0.5,0.6,1.2,0.5,0.0,0.3,1.5,1.3
34,28,Ron Baker,SG,25,WAS,4,0,11.3,0.0,1.0,...,NaN,0.0,1.0,1.0,0.5,0.3,0.3,0.5,0.5,0.0
35,29,Wade Baldwin,PG,22,POR,16,0,5.9,0.6,2.1,...,.727,0.1,0.8,0.9,0.8,0.1,0.1,0.9,0.7,1.9
36,30,Lonzo Ball,PG,21,LAL,47,45,30.3,3.9,9.7,...,.417,1.1,4.2,5.3,5.4,1.5,0.4,2.2,2.4,9.9
37,31,Mo Bamba,C,20,ORL,47,1,16.3,2.5,5.2,...,.587,1.4,3.6,5.0,0.8,0.3,1.4,0.9,2.2,6.2
38,32,J.J. Barea,PG,34,DAL,38,0,19.8,4.2,10.1,...,.705,0.3,2.2,2.5,5.6,0.6,0.0,1.9,1.3,10.9
39,33,Harrison Barnes,PF-SF,26,TOT,77,77,32.9,5.6,13.3,...,.824,0.7,3.9,4.7,1.5,0.6,0.2,1.3,1.6,16.4

In [78]:
nba = nba.drop(list(range(22, nba.shape[0] + 1, 20)))

KeyError: '[ 22  42  62  82 102 122 142 162 182 202 222 242 262 282 302 322 342 362\n 382 402 422 442 462 482 502 522 542 562 582 602 622 642 662 682] not found in axis'

In [77]:
range(22, nba.shape[0] + 1, 20)

range(22, 699, 20)

In [84]:
list(range(22, nba.shape[0] + 1, 20))

[22,
 42,
 62,
 82,
 102,
 122,
 142,
 162,
 182,
 202,
 222,
 242,
 262,
 282,
 302,
 322,
 342,
 362,
 382,
 402,
 422,
 442,
 462,
 482,
 502,
 522,
 542,
 562,
 582,
 602,
 622,
 642,
 662,
 682]

In [68]:
nba.head(40)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,PG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
22,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7
25,23,Trevor Ariza,SF,33,TOT,69,69,34.0,4.3,10.7,...,.793,0.7,4.7,5.4,3.7,1.3,0.3,1.5,1.9,12.5
26,23,Trevor Ariza,SF,33,PHO,26,26,34.0,3.3,8.7,...,.837,0.6,5.0,5.6,3.3,1.5,0.3,1.5,1.7,9.9
27,23,Trevor Ariza,SF,33,WAS,43,43,34.1,4.8,11.8,...,.777,0.8,4.5,5.3,3.8,1.2,0.3,1.6,2.0,14.1
28,24,D.J. Augustin,PG,31,ORL,81,81,28.0,3.9,8.4,...,.866,0.5,2.0,2.5,5.3,0.6,0.0,1.6,1.4,11.7
29,25,Deandre Ayton,C,20,PHO,71,70,30.7,7.2,12.3,...,.746,3.1,7.1,10.3,1.8,0.9,0.9,1.8,2.9,16.3
30,26,Dwayne Bacon,SG,23,CHO,43,13,17.7,2.8,6.0,...,.739,0.2,1.9,2.1,1.1,0.3,0.1,0.4,1.7,7.3
31,27,Marvin Bagley III,PF,19,SAC,62,4,25.3,5.7,11.4,...,.691,2.6,5.0,7.6,1.0,0.5,1.0,1.6,1.9,14.9
32,28,Ron Baker,SG,25,TOT,15,0,10.1,0.3,1.3,...,.833,0.1,0.7,0.7,1.0,0.4,0.1,0.3,1.2,0.9
33,28,Ron Baker,SG,25,NYK,11,0,9.7,0.4,1.5,...,.833,0.1,0.5,0.6,1.2,0.5,0.0,0.3,1.5,1.3
34,28,Ron Baker,SG,25,WAS,4,0,11.3,0.0,1.0,...,NaN,0.0,1.0,1.0,0.5,0.3,0.3,0.5,0.5,0.0
35,29,Wade Baldwin,PG,22,POR,16,0,5.9,0.6,2.1,...,.727,0.1,0.8,0.9,0.8,0.1,0.1,0.9,0.7,1.9
36,30,Lonzo Ball,PG,21,LAL,47,45,30.3,3.9,9.7,...,.417,1.1,4.2,5.3,5.4,1.5,0.4,2.2,2.4,9.9
37,31,Mo Bamba,C,20,ORL,47,1,16.3,2.5,5.2,...,.587,1.4,3.6,5.0,0.8,0.3,1.4,0.9,2.2,6.2
38,32,J.J. Barea,PG,34,DAL,38,0,19.8,4.2,10.1,...,.705,0.3,2.2,2.5,5.6,0.6,0.0,1.9,1.3,10.9
39,33,Harrison Barnes,PF-SF,26,TOT,77,77,32.9,5.6,13.3,...,.824,0.7,3.9,4.7,1.5,0.6,0.2,1.3,1.6,16.4

In [79]:
[1, 2, 3]

[1, 2, 3]

In [94]:
nba.drop(list(range(22, 29, 2)))

KeyError: '[22] not found in axis'

In [87]:
nba.shape[0]

698

In [95]:
list(range(22, nba.shape[0] + 1, 20))

[22,
 42,
 62,
 82,
 102,
 122,
 142,
 162,
 182,
 202,
 222,
 242,
 262,
 282,
 302,
 322,
 342,
 362,
 382,
 402,
 422,
 442,
 462,
 482,
 502,
 522,
 542,
 562,
 582,
 602,
 622,
 642,
 662,
 682]

In [97]:
nba.head(25)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,PG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7
25,23,Trevor Ariza,SF,33,TOT,69,69,34.0,4.3,10.7,...,.793,0.7,4.7,5.4,3.7,1.3,0.3,1.5,1.9,12.5

In [99]:
round?

Signature: round(number, ndigits=None)
Docstring:
Round a number to a given precision in decimal digits.

The return value is an integer if ndigits is omitted or None.  Otherwise
the return value has the same type as the number.  ndigits may be negative.
Type:      builtin_function_or_method